import React, { useState, useEffect } from 'react';
import axios from 'axios';
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';
import { useCity } from '../context/CityContext'; 
const API_BASE_URL = 'https://weather-backend-api-u29m.onrender.com';

const formatAxisDate = (dateString) => {
  const date = new Date(dateString);
  return `${date.getMonth() + 1}/${date.getDate()}`;
};

const formatTooltipLabel = (dateString) => {
  const date = new Date(dateString);
  return date.toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric' });
};

const PredictionPage = () => {
  const [prediction, setPrediction] = useState([]);
  const { city } = useCity(); 

  useEffect(() => {
    const fetchPrediction = async () => {
      try {
        const res = await axios.get(`${API_BASE_URL}/predict/${city}`);
        setPrediction(res.data);
      } catch (error) {
        console.error("Error fetching prediction:", error);
        setPrediction([]);
      }
    };

    fetchPrediction();
  }, [city]); 

  return (
    <div className="card">
      <h2>7-Day Predicted Temperature</h2>
      <p>This graph shows a 7-day forecast generated by our system's prediction model.</p>

      <div className="graph-card">
        <ResponsiveContainer width="100%" height={400}>
          <LineChart 
            data={prediction}
            margin={{ top: 5, right: 30, left: 0, bottom: 5 }}
          >
            <CartesianGrid strokeDasharray="3 3" stroke="#333" />
            <XAxis 
              dataKey="date"
              tickFormatter={formatAxisDate} 
              stroke="#aaa" 
              interval={0}
            />
            <YAxis 
              dataKey="temperature" 
              unit="°C"
              stroke="#aaa" 
            />
            <Tooltip 
              contentStyle={{ backgroundColor: '#222', border: 'none' }} 
              labelStyle={{ color: '#fff', fontWeight: 'bold' }}
              labelFormatter={formatTooltipLabel} 
            />
            <Line 
              type="monotone" 
              dataKey="temperature" 
              stroke="#00C49F"
              strokeWidth={2}
              activeDot={{ r: 8 }} 
            />
          </LineChart>
        </ResponsiveContainer>
      </div>
    </div>
  );
};

export default PredictionPage;
